# Question 2

## Imoprt relevant modules and packages

In [1]:
import numpy as np 
from ldpc import * 

## 2.1

In [2]:
H = np.array([[1, 1, 1, 1, 0, 0],
              [0, 0, 1, 1, 0, 1],
              [1, 0, 0, 1, 1, 0]], dtype=int)

In [3]:
h2, G = enocding(H)

In [4]:
print(h2)

[[1 0 0 1 1 0]
 [0 1 0 1 1 1]
 [0 0 1 1 0 1]]


In [5]:
print(G)

[[1 1 0]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


## 2.3

In [6]:
# read data
h = np.array(read_h('../../data/ldpc/H1.txt'))
y = np.array(read_y('../../data/ldpc/y1.txt'))

In [7]:
code, num, decoded = decoding(h, y)

In [8]:
print(f" The output code: {code} \n The nummber of iterations: {num}")

 The output code: 0 
 The nummber of iterations: 8


In [9]:
print(decoded)

[0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1
 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1
 1 0 1 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 1 1 0 0 1
 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 1 0 1 0 1 1 0
 1 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 0 0
 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 1 1 0 0 1 1 0 1 0
 1 0 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1
 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1
 1 0 0 1 1 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 0 0
 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 1 0 1
 0 0 1 0 1 1 0 0 1 1 0 1 

## 2.4

In [10]:
decoded.shape

(1000,)

In [11]:
res = decoded.astype(str).reshape(125, 8)[:31]
binary_chars = [''.join(r) for r in res]
message = [chr(int(binary_char, 2)) for binary_char in binary_chars]


In [12]:
print(''.join(message))

Happy Holidays! Dmitry&David :)
