# Question 1.3

## Import relevant packages

In [1]:
import numpy as np 
from threewhether import * 

## 1.3.2 Random initialisation

In [2]:
num_of_iteration = 20
data = read_data('../../data/meteo1.csv')

In [3]:

mle_params = EM_Mixture_Markov(data, num_of_iteration)

for name, i in zip(['Hidden State Prob:', 'Initial State Prob Given Hidden State:',
                    'Transition Matrix Given Hidden State:'],
                    mle_params):
    print(name,'\n', np.round(i, 3))

Iteration: 1  The loglikelihood: -56909.045
Iteration: 2  The loglikelihood: -45635.671
Iteration: 3  The loglikelihood: -45293.055
Iteration: 4  The loglikelihood: -45255.235
Iteration: 5  The loglikelihood: -45254.517
Iteration: 6  The loglikelihood: -45254.510
Iteration: 7  The loglikelihood: -45254.510
Iteration: 8  The loglikelihood: -45254.510
Iteration: 9  The loglikelihood: -45254.510
Iteration: 10  The loglikelihood: -45254.510
Iteration: 11  The loglikelihood: -45254.510
Iteration: 12  The loglikelihood: -45254.510
Iteration: 13  The loglikelihood: -45254.510
Iteration: 14  The loglikelihood: -45254.510
Iteration: 15  The loglikelihood: -45254.510
Iteration: 16  The loglikelihood: -45254.510
Iteration: 17  The loglikelihood: -45254.510
Iteration: 18  The loglikelihood: -45254.510
Iteration: 19  The loglikelihood: -45254.510
Iteration: 20  The loglikelihood: -45254.510
Hidden State Prob: 
 [0.3   0.192 0.508]
Initial State Prob Given Hidden State: 
 [[0.192 0.419 0.389]
 [0.42

## 1.3.4 Uniform initialisation

In [4]:
mle_params = EM_Mixture_Markov(data, num_of_iteration,
                               initial='Uniform')

for name, i in zip(['Hidden State Prob:', 'Initial State Prob Given Hidden State:',
                    'Transition Matrix Given Hidden State:'],
                    mle_params):
    print(name,'\n', np.round(i, 3))

Iteration: 1  The loglikelihood: -54930.614
Iteration: 2  The loglikelihood: -49473.547
Iteration: 3  The loglikelihood: -49473.547
Iteration: 4  The loglikelihood: -49473.547
Iteration: 5  The loglikelihood: -49473.547
Iteration: 6  The loglikelihood: -49473.547
Iteration: 7  The loglikelihood: -49473.547
Iteration: 8  The loglikelihood: -49473.547
Iteration: 9  The loglikelihood: -49473.547
Iteration: 10  The loglikelihood: -49473.547
Iteration: 11  The loglikelihood: -49473.547
Iteration: 12  The loglikelihood: -49473.547
Iteration: 13  The loglikelihood: -49473.547
Iteration: 14  The loglikelihood: -49473.547
Iteration: 15  The loglikelihood: -49473.547
Iteration: 16  The loglikelihood: -49473.547
Iteration: 17  The loglikelihood: -49473.547
Iteration: 18  The loglikelihood: -49473.547
Iteration: 19  The loglikelihood: -49473.547
Iteration: 20  The loglikelihood: -49473.547
Hidden State Prob: 
 [0.333 0.333 0.333]
Initial State Prob Given Hidden State: 
 [[0.374 0.404 0.222]
 [0.37